### ISSUE TITLE
Incorrect results for TCP on all OS platforms

### ISSUE THREAD

**Issue by Xymox1** [White-Tiger/WinMTR#8]
MTR reports really incorrect results for its last hop when doing TCP. A discussion of this issue is here https://www.dslreports.com/forum/r31122204-SB6190-Puma6-TCP-UDP-Network-Latency-Issue-Discussion~start=4592

**Comment by White-Tiger** [comment]
sorry but this isn't MTR... it's WinMTR which is entirely different
